### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by Sherwin-14**
I have added the basic outlay .

### CODE REVIEW

**Review by A91y — COMMENTED** [review]
Nice work! More information can be added, for example, about LabelEncoder..

**Comment by Sherwin-14** [comment]
Please list all the suggestions/improvements that can be made

**Comment by A91y** [comment]
> Please list all the suggestions/improvements that can be made

1. Results and Performance:
Briefly summarize the model's performance, emphasizing key metrics like accuracy.

2. LabelEncoder Explanation:
Motive of using LabelEncoder and how it works (just an overview)

Else everything looks good to me..

**Comment by A91y** [comment]
LGTM...

**Pull request merged**
